apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  namespace: test1
spec:
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP