apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  namespace: test1
spec:
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP