apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: {{ .Release.Name }}
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api-app
          image: habor.analytichpxv3.online/api:{{ .Values.IMAGE_TAG }}
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: API_KEY
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: VERSION