apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  namespace: {{ .Release.Name }}
  labels:
    app: ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app
          image: habor.analytichpxv3.online/ui:test  # Replace with your image
          ports:
            - containerPort: 5173