apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Name }}
  labels:
    app: api-app
data:
  VERSION: {{ .Values.VERSION | quote }}
  API_KEY: {{ .Values.API_KEY }}
